name = "CobbleUwU"
author = "jadelily18, SkywardMC"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcdf125267bc796cf7447c2cf0098e350abdcc8c9aef7fe05e984dd68fb0baba"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
