name = "CobbleUwU"
author = "jadelily18, SkywardMC"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b9c901c0c7bdc9b5d1f77d8e915ba8d05d448edb93b10744681b876fbcc3a65"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
