name = "CobbleUwU"
author = "jadelily18, SkywardMC"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1ba8492d707c4449e03964414c31df95b6ca96573b516647d13d69af2bf4971"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
